version: '3'
services:
  db:
    image: postgres:11.1-alpine
  api:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    container_name: giraffe-api
    volumes:
      - ./:/giraffecms
    working_dir: /giraffecms
    ports:
      - "3000:3000"
    depends_on:
    - db
