version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: ruby:2.6.2
        environment:
          BUNDLE_JOBS: 2
          BUNDLE_RETRY: 2
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: stjorn
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: gfcms
          POSTGRES_DB: gfcms-dev
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install
      
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run all Rspec tests
          command: bundle exec rspec