default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gfcms-dev
  password:

test:
  <<: *default
  database: gfcms-test
  password: